spring:
  config:
    activate:
      on-profile: test

  liquibase:
    enabled: false

  datasource:
    url: jdbc:h2:mem:shareit_tdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect