spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:shareit_tdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: shareit
    password: shareit
    driver-class-name: org.h2.Driver  # Важно: указываем драйвер H2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
